version: '3.3'

services:
  postgres2:
    image: postgres:latest
    environment:
      - POSTGRES_DB=my_inventory
      - POSTGRES_USER=appadmin
      - POSTGRES_PASSWORD=Man12345.
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin2:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80


